### ISSUE TITLE
An error is displayed when accessing the ADAPH.TxSubmit page

### ISSUE THREAD

**Issue by btbf** [ADAPhilippines/ADAPH.TxSubmit#2]
When accessing https://node.xstakepool.com/, a large number of errors are displayed in the server log.

```
~/git/ADAPH.TxSubmit$ ./start.sh
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  ADAPH.TxSubmit -> /home/btbf/git/ADAPH.TxSubmit/bin/Release/net6.0/ADAPH.TxSubmit.dll
  ADAPH.TxSubmit -> /home/btbf/git/ADAPH.TxSubmit/bin/Release/net6.0/publish/
info: ADAPH.TxSubmit.Workers.DbWorker[0]
      Refreshing data
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:1337
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /home/btbf/git/ADAPH.TxSubmit/
info: ADAPH.TxSubmit.Workers.TransactionWorker[0]
      Checking for unconfirmed transactions: 0
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Could not find 'mudResizeListenerFactory.listenForResize' ('mudResizeListenerFactory' was undefined).
      Error: Could not find 'mudResizeListenerFactory.listenForResize' ('mudResizeListenerFactory' was undefined).
          at https://node.xstakepool.com/_framework/blazor.server.js:1:497
          at Array.forEach (<anonymous>)
          at i.findFunction (https://node.xstakepool.com/_framework/blazor.server.js:1:465)
          at E (https://node.xstakepool.com/_framework/blazor.server.js:1:2606)
          at https://node.xstakepool.com/_framework/blazor.server.js:1:3494
          at new Promise (<anonymous>)
          at Tt.beginInvokeJSFromDotNet (https://node.xstakepool.com/_framework/blazor.server.js:1:3475)
          at https://node.xstakepool.com/_framework/blazor.server.js:1:71783
          at Array.forEach (<anonymous>)
          at Tt._invokeClientMethod (https://node.xstakepool.com/_framework/blazor.server.js:1:71769)
      Microsoft.JSInterop.JSException: Could not find 'mudResizeListenerFactory.listenForResize' ('mudResizeListenerFactory' was undefined).
      Error: Could not find 'mudResizeListenerFactory.listenForResize' ('mudResizeListenerFactory' was undefined).
          at https://node.xstakepool.com/_framework/blazor.server.js:1:497
          at Array.forEach (<anonymous>)
          at i.findFunction (https://node.xstakepool.com/_framework/blazor.server.js:1:465)
          at E (https://node.xstakepool.com/_framework/blazor.server.js:1:2606)
          at https://node.xstakepool.com/_framework/blazor.server.js:1:3494
          at new Promise (<anonymous>)
          at Tt.beginInvokeJSFromDotNet (https://node.xstakepool.com/_framework/blazor.server.js:1:3475)
          at https://node.xstakepool.com/_framework/blazor.server.js:1:71783
          at Array.forEach (<anonymous>)
          at Tt._invokeClientMethod (https://node.xstakepool.com/_framework/blazor.server.js:1:71769)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at MudBlazor.Services.BreakpointService.Subscribe(Action`1 callback, ResizeOptions options)
         at MudBlazor.Services.BreakpointService.Subscribe(Action`1 callback)
         at MudBlazor.MudBreakpointProvider.OnAfterRenderAsync(Boolean firstRender)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit '5SiSu6_AXZs-d9B0LJrbITnu9VPgM4OvKyOyzo-l-JY'.
      Microsoft.JSInterop.JSException: Could not find 'mudResizeListenerFactory.listenForResize' ('mudResizeListenerFactory' was undefined).
      Error: Could not find 'mudResizeListenerFactory.listenForResize' ('mudResizeListenerFactory' was undefined).
          at https://node.xstakepool.com/_framework/blazor.server.js:1:497
          at Array.forEach (<anonymous>)
          at i.findFunction (https://node.xstakepool.com/_framework/blazor.server.js:1:465)
          at E (https://node.xstakepool.com/_framework/blazor.server.js:1:2606)
          at https://node.xstakepool.com/_framework/blazor.server.js:1:3494
          at new Promise (<anonymous>)
          at Tt.beginInvokeJSFromDotNet (https://node.xstakepool.com/_framework/blazor.server.js:1:3475)
          at https://node.xstakepool.com/_framework/blazor.server.js:1:71783
          at Array.forEach (<anonymous>)
          at Tt._invokeClientMethod (https://node.xstakepool.com/_framework/blazor.server.js:1:71769)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at MudBlazor.Services.BreakpointService.Subscribe(Action`1 callback, ResizeOptions options)
         at MudBlazor.Services.BreakpointService.Subscribe(Action`1 callback)
         at MudBlazor.MudBreakpointProvider.OnAfterRenderAsync(Boolean firstRender)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Could not find 'mudKeyInterceptor.connect' ('mudKeyInterceptor' was undefined).
      Error: Could not find 'mudKeyInterceptor.connect' ('mudKeyInterceptor' was undefined).
          at https://node.xstakepool.com/_framework/blazor.server.js:1:497
          at Array.forEach (<anonymous>)
          at i.findFunction (https://node.xstakepool.com/_framework/blazor.server.js:1:465)
          at E (https://node.xstakepool.com/_framework/blazor.server.js:1:2606)
          at https://node.xstakepool.com/_framework/blazor.server.js:1:3494
          at new Promise (<anonymous>)
          at Tt.beginInvokeJSFromDotNet (https://node.xstakepool.com/_framework/blazor.server.js:1:3475)
          at https://node.xstakepool.com/_framework/blazor.server.js:1:71783
          at Array.forEach (<anonymous>)
          at Tt._invokeClientMethod (https://node.xstakepool.com/_framework/blazor.server.js:1:71769)
      Microsoft.JSInterop.JSException: Could not find 'mudKeyInterceptor.connect' ('mudKeyInterceptor' was undefined).
      Error: Could not find 'mudKeyInterceptor.connect' ('mudKeyInterceptor' was undefined).
          at https://node.xstakepool.com/_framework/blazor.server.js:1:497
          at Array.forEach (<anonymous>)
          at i.findFunction (https://node.xstakepool.com/_framework/blazor.server.js:1:465)
          at E (https://node.xstakepool.com/_framework/blazor.server.js:1:2606)
          at https://node.xstakepool.com/_framework/blazor.server.js:1:3494
          at new Promise (<anonymous>)
          at Tt.beginInvokeJSFromDotNet (https://node.xstakepool.com/_framework/blazor.server.js:1:3475)
          at https://node.xstakepool.com/_framework/blazor.server.js:1:71783
          at Array.forEach (<anonymous>)
          at Tt._invokeClientMethod (https://node.xstakepool.com/_framework/blazor.server.js:1:71769)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at MudBlazor.Services.KeyInterceptor.Connect(String elementId, KeyInterceptorOptions options)
         at MudBlazor.MudSwitch`1.OnAfterRenderAsync(Boolean firstRender)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit '5SiSu6_AXZs-d9B0LJrbITnu9VPgM4OvKyOyzo-l-JY'.
      Microsoft.JSInterop.JSException: Could not find 'mudKeyInterceptor.connect' ('mudKeyInterceptor' was undefined).
      Error: Could not find 'mudKeyInterceptor.connect' ('mudKeyInterceptor' was undefined).
          at https://node.xstakepool.com/_framework/blazor.server.js:1:497
          at Array.forEach (<anonymous>)
          at i.findFunction (https://node.xstakepool.com/_framework/blazor.server.js:1:465)
          at E (https://node.xstakepool.com/_framework/blazor.server.js:1:2606)
          at https://node.xstakepool.com/_framework/blazor.server.js:1:3494
          at new Promise (<anonymous>)
          at Tt.beginInvokeJSFromDotNet (https://node.xstakepool.com/_framework/blazor.server.js:1:3475)
          at https://node.xstakepool.com/_framework/blazor.server.js:1:71783
          at Array.forEach (<anonymous>)
          at Tt._invokeClientMethod (https://node.xstakepool.com/_framework/blazor.server.js:1:71769)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at MudBlazor.Services.KeyInterceptor.Connect(String elementId, KeyInterceptorOptions options)
         at MudBlazor.MudSwitch`1.OnAfterRenderAsync(Boolean firstRender)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Could not find 'mudResizeObserver.connect' ('mudResizeObserver' was undefined).
      Error: Could not find 'mudResizeObserver.connect' ('mudResizeObserver' was undefined).
          at https://node.xstakepool.com/_framework/blazor.server.js:1:497
          at Array.forEach (<anonymous>)
          at i.findFunction (https://node.xstakepool.com/_framework/blazor.server.js:1:465)
          at E (https://node.xstakepool.com/_framework/blazor.server.js:1:2606)
          at https://node.xstakepool.com/_framework/blazor.server.js:1:3494
          at new Promise (<anonymous>)
          at Tt.beginInvokeJSFromDotNet (https://node.xstakepool.com/_framework/blazor.server.js:1:3475)
          at https://node.xstakepool.com/_framework/blazor.server.js:1:71783
          at Array.forEach (<anonymous>)
          at Tt._invokeClientMethod (https://node.xstakepool.com/_framework/blazor.server.js:1:71769)
      Microsoft.JSInterop.JSException: Could not find 'mudResizeObserver.connect' ('mudResizeObserver' was undefined).
      Error: Could not find 'mudResizeObserver.connect' ('mudResizeObserver' was undefined).
          at https://node.xstakepool.com/_framework/blazor.server.js:1:497
          at Array.forEach (<anonymous>)
          at i.findFunction (https://node.xstakepool.com/_framework/blazor.server.js:1:465)
          at E (https://node.xstakepool.com/_framework/blazor.server.js:1:2606)
          at https://node.xstakepool.com/_framework/blazor.server.js:1:3494
          at new Promise (<anonymous>)
          at Tt.beginInvokeJSFromDotNet (https://node.xstakepool.com/_framework/blazor.server.js:1:3475)
          at https://node.xstakepool.com/_framework/blazor.server.js:1:71783
          at Array.forEach (<anonymous>)
          at Tt._invokeClientMethod (https://node.xstakepool.com/_framework/blazor.server.js:1:71769)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at MudBlazor.Services.ResizeObserver.Observe(IEnumerable`1 elements)
         at MudBlazor.MudTabs.OnAfterRenderAsync(Boolean firstRender)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit '5SiSu6_AXZs-d9B0LJrbITnu9VPgM4OvKyOyzo-l-JY'.
      Microsoft.JSInterop.JSException: Could not find 'mudResizeObserver.connect' ('mudResizeObserver' was undefined).
      Error: Could not find 'mudResizeObserver.connect' ('mudResizeObserver' was undefined).
          at https://node.xstakepool.com/_framework/blazor.server.js:1:497
          at Array.forEach (<anonymous>)
          at i.findFunction (https://node.xstakepool.com/_framework/blazor.server.js:1:465)
          at E (https://node.xstakepool.com/_framework/blazor.server.js:1:2606)
          at https://node.xstakepool.com/_framework/blazor.server.js:1:3494
          at new Promise (<anonymous>)
          at Tt.beginInvokeJSFromDotNet (https://node.xstakepool.com/_framework/blazor.server.js:1:3475)
          at https://node.xstakepool.com/_framework/blazor.server.js:1:71783
          at Array.forEach (<anonymous>)
          at Tt._invokeClientMethod (https://node.xstakepool.com/_framework/blazor.server.js:1:71769)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at MudBlazor.Services.ResizeObserver.Observe(IEnumerable`1 elements)
         at MudBlazor.MudTabs.OnAfterRenderAsync(Boolean firstRender)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: The given key '10920015-8df9-43f0-be9c-7e5ca4cb8e3d' was not present in the dictionary.
      System.Collections.Generic.KeyNotFoundException: The given key '10920015-8df9-43f0-be9c-7e5ca4cb8e3d' was not present in the dictionary.
         at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
         at MudBlazor.Services.BreakpointService.Subscribe(Action`1 callback, ResizeOptions options)
         at MudBlazor.Services.BreakpointService.Subscribe(Action`1 callback)
         at MudBlazor.MudHidden.OnAfterRenderAsync(Boolean firstRender)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit '5SiSu6_AXZs-d9B0LJrbITnu9VPgM4OvKyOyzo-l-JY'.
      System.Collections.Generic.KeyNotFoundException: The given key '10920015-8df9-43f0-be9c-7e5ca4cb8e3d' was not present in the dictionary.
         at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
         at MudBlazor.Services.BreakpointService.Subscribe(Action`1 callback, ResizeOptions options)
         at MudBlazor.Services.BreakpointService.Subscribe(Action`1 callback)
         at MudBlazor.MudHidden.OnAfterRenderAsync(Boolean firstRender)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: The given key '10920015-8df9-43f0-be9c-7e5ca4cb8e3d' was not present in the dictionary.
      System.Collections.Generic.KeyNotFoundException: The given key '10920015-8df9-43f0-be9c-7e5ca4cb8e3d' was not present in the dictionary.
         at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
         at MudBlazor.Services.BreakpointService.Subscribe(Action`1 callback, ResizeOptions options)
         at MudBlazor.Services.BreakpointService.Subscribe(Action`1 callback)
         at MudBlazor.MudHidden.OnAfterRenderAsync(Boolean firstRender)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit '5SiSu6_AXZs-d9B0LJrbITnu9VPgM4OvKyOyzo-l-JY'.
      System.Collections.Generic.KeyNotFoundException: The given key '10920015-8df9-43f0-be9c-7e5ca4cb8e3d' was not present in the dictionary.
         at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
         at MudBlazor.Services.BreakpointService.Subscribe(Action`1 callback, ResizeOptions options)
         at MudBlazor.Services.BreakpointService.Subscribe(Action`1 callback)
         at MudBlazor.MudHidden.OnAfterRenderAsync(Boolean firstRender)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

What's wrong with this?

**Comment by btbf** [comment]
https://mudblazor.com/getting-started/installation#online-playground
Do I need to install this one?

**Comment by Mercurial** [comment]
your issue seems to be related to the way you are setting up your web server or reverse proxy, we don't recommend exposing the tx-submit server directly but instead it should be reverse proxied via nginx or apache.

**Comment by btbf** [comment]
Thank you for your answer.
https://node.xstakepool.com/ This address is set up as a reverse proxy in apache.
And,https://(serverIP):1337/ had also the same error when I published it.

_content/MudBlazor/MudBlazor.min.js
_content/MudBlazor/MudBlazor.min.css
What could cause these files to 404 not found?

**Comment by Mercurial** [comment]
hey you are right, this was a mistake from my part. There was something wrong with the `./start.sh` script.

But it should be fixed now this commit: https://github.com/ADAPhilippines/ADAPH.TxSubmit/commit/09d8556a9cd23807a22206351bf5a1c6d61fcd49

Let me know if you are still having any issues.

Thank you for finding this error!
